---

registry: ghcr.io
labels:
  org.opencontainers.image.licenses: GPL-2.0-only
  org.opencontainers.image.title: Weekly updated Google Gemini CLI Docker image
  org.opencontainers.image.description: |
    Those images are just standard Gemini CLI base images, but:

    1. Updated weekly for security.
    2. Optimized for smaller size.

platforms:
  - linux/amd64
  - linux/arm64

images:
  gemini-cli:
    dockerfile: Dockerfile
    args:
      GEMINI_CLI_VERSION: "{{ env \"GEMINI_CLI_VERSION\" | default \"latest\" }}"
    tags:
      - ghcr.io/ly4096x/gemini-cli:build-v{{ .tag }}
      - ghcr.io/ly4096x/gemini-cli:v{{ env "GEMINI_CLI_VERSION" }}
      - ghcr.io/ly4096x/gemini-cli:v{{ env "GEMINI_CLI_VERSION" | splitList "." | first }}
      - ghcr.io/ly4096x/gemini-cli:v{{ env "GEMINI_CLI_VERSION" | splitList "." | first }}.{{ env "GEMINI_CLI_VERSION" | splitList "." | rest | first }}
      - ghcr.io/ly4096x/gemini-cli:latest
